name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  REGISTRY2: quay.io
  REGISTRY3: docker.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG:  0.${{ github.RUN_NUMBER }}.0  #//${{ github.sha }}

permissions:
  packages: write

jobs:

  build:

    runs-on: ubuntu-latest
    steps:

      - name: Log in to the GHCR Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.REGISTRY }}/vishalmamidi/fluentd-opensearch:1.0.0

